spring:
  application:
    name: agent-task
  redis:
    host: 192.168.1.10
    database: 6

fox:
  security:
    oauth2:
      clients[0]:
        clientId: fox
        clientSecret: foxsecret
        accessTokenValidateSeconds: 3600